### ISSUE TITLE
"Cannot use sysprep..." Error from playbook  when  using cloud-init only deployment

### ISSUE THREAD

**Issue by eslutsky** [oVirt/ovirt-ansible-vm-infra#104]
running playbook with parameters:

Resulting error:
2019-07-14 09:48:03,868 p=10844 u=root |  Using module file /usr/lib/python2.7/site-packages/ansible/modules/utilities/logic/async_status.py
2019-07-14 09:48:04,026 p=10844 u=root |  The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ovirt_vm_payload_txFuqn/__main__.py", line 2071, in main
    ) else None,
  File "/tmp/ansible_ovirt_vm_payload_txFuqn/ansible_ovirt_vm_payload.zip/ansible/module_utils/ovirt.py", line 738, in action
    getattr(entity_service, action)(**kwargs)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 31504, in start
    return self._internal_action(action, 'start', None, headers, query, wait)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 299, in _internal_action
    return future.wait() if wait else future
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 55, in wait
    return self._code(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 296, in callback
    self._check_fault(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 132, in _check_fault
    self._raise_error(response, body)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 118, in _raise_error
    raise error
Error: Fault reason is "Cannot use sysprep and cloud_init tags simultaneously when running VM.". HTTP response code is 409.

Full Log:
https://paste.fedoraproject.org/paste/vCsDHnqdjqpohJ9HvtC9FA/raw

**Comment by eslutsky** [comment]
suspect that sysprep parameter is  propagated by mistake as empty dict to the : 

https://github.com/oVirt/ovirt-ansible-vm-infra/blob/e734783f54e3010ae73b6f2cb9136478ad4ad115/tasks/manage_state.yml#L64

**Comment by tiraboschi** [comment]
> suspect that sysprep parameter is propagated by mistake as empty dict to the :
> 
> https://github.com/oVirt/ovirt-ansible-vm-infra/blob/e734783f54e3010ae73b6f2cb9136478ad4ad115/tasks/manage_state.yml#L64

Yes, please see: https://github.com/ansible/ansible/issues/44261#issuecomment-413564998

**Comment by machacekondra** [comment]
@mnecas Can you please take a look

**Comment by mnecas** [comment]
Hi @eslutsky can you give me your playbook so i can try to recreate it?

**Comment by eslutsky** [comment]
> Hi @eslutsky can you give me your playbook so i can try to recreate it?

Sure,
you can use this playbook:
https://paste.fedoraproject.org/paste/OMr4EehXONbjcKNcHsuvNg
during execution this error received:
TASK [ovirt.vm-infra : Wait for VMs to be started] ****************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Error: Fault reason is "Cannot use sysprep and cloud_init tags simultaneously when running VM.". HTTP response code is 409.
failed: [localhost] (item={'failed': False, u'finished': 0, u'results_file': u'/root/.ansible_async/270615310005.13509', u'ansible_job_id': u'270615310005.13509', u'started': 1, 'changed': False}) => {"ansible_job_id": "270615310005.13509", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "270615310005.13509", "changed": false, "failed": false, "finished": 0, "results_file": "/root/.ansible_async/270615310005.13509", "started": 1}, "msg": "Fault reason is \"Cannot use sysprep and cloud_init tags simultaneously when running VM.\". HTTP response code is 409."}

TASK [ovirt.vm-infra : Unset facts] *******************************************************************************************************************************************************************************
ok: [localhost]

TASK [ovirt.vm-infra : Logout from oVirt] *************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=19   changed=0    unreachable=0    failed=1

**Comment by mnecas** [comment]
@eslutsky thank you for the playbook, really helped.

**Comment by mnecas** [comment]
Backport https://github.com/ansible/ansible/pull/59286

**Comment by machacekondra** [comment]
Will work from Ansible 2.8.3
