### ISSUE TITLE
Using the ovirt_vm_infra.yml example with -C option, fails to find the 'ovirt_vms' variable

### ISSUE THREAD

**Issue by stvnrsnbrg** [oVirt/ovirt-ansible-vm-infra#11]
[ovirt_vm_infra.txt](https://github.com/oVirt/ovirt-ansible-vm-infra/files/1755819/ovirt_vm_infra.txt)

As per the attached dump file ovirt_vm_infra.txt, when running the ovirt_vm_infra.yml example with the -C option, not all libraries seems to be brought in so the 'ovirt_vms' variable is not defined. Removing the -C option resolves this error, but -C should still work for checking.

Command line example:

ansible-playbook -C -vvv ovirt_vm_infra.yml

Error:

fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ovirt_vms' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/oVirt.vm-infra/tasks/create_vms.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Create VM {{current_vm.name }}\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'ovirt_vms' is undefined"

Compressed file with yml example:

[ovirt_vm_infra.tar.gz](https://github.com/oVirt/ovirt-ansible-vm-infra/files/1755829/ovirt_vm_infra.tar.gz)

Note: use "tar xvzf  ovirt_vm_infra.tar.gz"

**Comment by KKoukiou** [comment]
@stvnrsnbrg Hey, i tried to reproduce locally with master and I can't. Instead I am getting the following:

``` bash
(ansible) [kkoukiou@katerina ovirt-ansible-infra]$ ansible-playbook -C -i inventory test.yaml 
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed 
in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will 
be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [oVirt infra] ***************************************************************************************************************************************************************************

TASK [oVirt.vm-infra : Login to oVirt] *******************************************************************************************************************************************************
skipping: [localhost]

TASK [oVirt.vm-infra : Create VMs] ***********************************************************************************************************************************************************
included: /home/kkoukiou/repos/oVirt/ovirt-ansible-vm-infra/tasks/create_vms.yml for localhost
included: /home/kkoukiou/repos/oVirt/ovirt-ansible-vm-infra/tasks/create_vms.yml for localhost
included: /home/kkoukiou/repos/oVirt/ovirt-ansible-vm-infra/tasks/create_vms.yml for localhost

TASK [oVirt.vm-infra : Create VM postgresql-vm-0] ********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "check mode and async cannot be used on same task."}

TASK [oVirt.vm-infra : Logout from oVirt] ****************************************************************************************************************************************************
skipping: [localhost]
	to retry, use: --limit @/home/kkoukiou/repos/oVirt/ovirt-ansible-infra/test.retry

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   
```

So I guess your issue does not reproduce any more, however you can not use this role in check mode, because of `check mode and async cannot be used on same task.`

**Comment by machacekondra** [comment]
Since this role is using async mechanism, it's not possible to support dry mode.
