### ISSUE TITLE
Getting a Type error from TASK [ovirt.vm-infra : Manage profile disks] while creating a VM

### ISSUE THREAD

**Issue by k8s-junkie** [oVirt/ovirt-ansible-vm-infra#114]
Created a playbook based on the yml present in the examples directory. Also created a template using the oVirt Manager GUI. Then ran the playbook to create VM and got the below error
TASK [ovirt.vm-infra : Manage profile disks] ***********************************************************************************************
task path: /home/vzuser/.ansible/roles/ovirt.vm-infra/tasks/vm_state_present.yml:20
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: vzuser
<127.0.0.1> EXEC /bin/sh -c 'echo ~vzuser && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vzuser/.ansible/tmp/ansible-tmp-1572014940.04-168949764695442 `" && echo ansible-tmp-1572014940.04-168949764695442="` echo /home/vzuser/.ansible/tmp/ansible-tmp-1572014940.04-168949764695442 `" ) && sleep 0'
Using module file /home/vzuser/.ansible/roles/ovirt.vm-infra/library/ovirt_disk29.py
<127.0.0.1> PUT /home/vzuser/.ansible/tmp/ansible-local-40761XnbS90/tmpHgElTl TO /home/vzuser/.ansible/tmp/ansible-tmp-1572014940.04-168949764695442/AnsiballZ_ovirt_disk29.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/vzuser/.ansible/tmp/ansible-tmp-1572014940.04-168949764695442/ /home/vzuser/.ansible/tmp/ansible-tmp-1572014940.04-168949764695442/AnsiballZ_ovirt_disk29.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/vzuser/.ansible/tmp/ansible-tmp-1572014940.04-168949764695442/AnsiballZ_ovirt_disk29.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/vzuser/.ansible/tmp/ansible-tmp-1572014940.04-168949764695442/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ovirt_disk29_payload_lx9eAp/__main__.py", line 720, in main
    force_create=force_create,
  File "/tmp/ansible_ovirt_disk29_payload_lx9eAp/ansible_ovirt_disk29_payload.zip/ansible/module_utils/ovirt.py", line 587, in create
    **kwargs
**TypeError: add() got an unexpected keyword argument 'force_create'**

failed: [localhost] (item=[{u'profile': {u'cluster': u'Default', u'state': u'running', u'tag': [u'gpuvm'], u'template': u'gpu_vm', u'memory': u'8GiB', u'cores': 4, u'memory_max': u'16GiB'}, u'cloud_init': {u'authorized_ssh_keys': u'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+pDYmBDdrnA+Q7OagFrJT/b0KD0iUNQDsRc+dJ5jm/nVW2jTURhk00kZUIPeVtY4vlZZ0o5GdWSQdp06UEH7hTAv1oKTOuZ3l/O2CiWYNk1WyPhAz08TzPSDngBVuEULjW1U1PasnZQfmyVxa9JoJSJ+niwYrPnI7AGn5k7VVCB7uA1ppCJARSeNS0RypMV4U8vkjJ2q5QurPCErYBnMbq184Ez8PpFnAEs7X5CUwSB4ByIsChMl/VP/BKLXmNTEcbAkbScX+0fEQtstWRHU9z7/E0z+j/TzSEMU+zYvSf/WvI/IBJdetY36O2JBSYkTVstVRFe7FzdOHA5OY3Lfj vzuser@ansible-server', u'user_name': u'vzuser', u'host_name': u'oci-gpu-node-01', u'root_password': u'******'}, u'tag': [u'gpunode'], u'name': u'oci-gpu-node-01', u'memory': u'8GiB'}, {u'interface': u'virtio', u'storage_domain': u'data', u'name': u'data', u'size': u'24GiB'}]) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "activate": true, 
            "auth": {
                "ca_file": "/home/vzuser/k8s-cluster-setup/mec-hw-deploy/certs/ovirt380.cer", 
                "compress": true, 
                "headers": null, 
                "insecure": true, 
                "kerberos": false, 
                "timeout": 0, 
                "token": "6HLfD7Q6btL7TtvMGUFd3cUKpGLNKFXKVjqGA2CgUWLEFPB3Dp1NiQX_SXNUQmTyyRAIiYIXZ3kBYDpHJJWIfw", 
                "url": "https://ovirt380.envrmnt.local/ovirt-engine/api"
            }, 
            "bootable": null, 
            "content_type": "data", 
            "description": null, 
            "download_image_path": null, 
            "fetch_nested": false, 
            "force": false, 
            "format": "cow", 
            "host": null, 
            "id": null, 
            "image_provider": null, 
            "interface": "virtio", 
            "logical_unit": null, 
            "name": "oci-gpu-node-01_data", 
            "nested_attributes": [], 
            "openstack_volume_type": null, 
            "poll_interval": 3, 
            "profile": null, 
            "quota_id": null, 
            "shareable": null, 
            "size": "24GiB", 
            "sparse": null, 
            "sparsify": null, 
            "state": "present", 
            "storage_domain": "data", 
            "storage_domains": null, 
            "timeout": 180, 
            "upload_image_path": null, 
            "vm_id": null, 
            "vm_name": "oci-gpu-node-01", 
            "wait": true, 
            "wipe_after_delete": null
        }
    }, 
    "item": [
        {
            "cloud_init": {
                "authorized_ssh_keys": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+pDYmBDdrnA+Q7OagFrJT/b0KD0iUNQDsRc+dJ5jm/nVW2jTURhk00kZUIPeVtY4vlZZ0o5GdWSQdp06UEH7hTAv1oKTOuZ3l/O2CiWYNk1WyPhAz08TzPSDngBVuEULjW1U1PasnZQfmyVxa9JoJSJ+niwYrPnI7AGn5k7VVCB7uA1ppCJARSeNS0RypMV4U8vkjJ2q5QurPCErYBnMbq184Ez8PpFnAEs7X5CUwSB4ByIsChMl/VP/BKLXmNTEcbAkbScX+0fEQtstWRHU9z7/E0z+j/TzSEMU+zYvSf/WvI/IBJdetY36O2JBSYkTVstVRFe7FzdOHA5OY3Lfj vzuser@ansible-server", 
                "host_name": "oci-gpu-node-01", 
                "root_password": "******", 
                "user_name": "vzuser"
            }, 
            "memory": "8GiB", 
            "name": "oci-gpu-node-01", 
            "profile": {
                "cluster": "Default", 
                "cores": 4, 
                "memory": "8GiB", 
                "memory_max": "16GiB", 
                "state": "running", 
                "tag": [
                    "gpuvm"
                ], 
                "template": "gpu_vm"
            }, 
            "tag": [
                "gpunode"
            ]
        }, 
        {
            "interface": "virtio", 
            "name": "data", 
            "size": "24GiB", 
            "storage_domain": "data"
        }
    ], 
    **"msg": "add() got an unexpected keyword argument 'force_create'"**
}
Read vars_file 'passwords.yml'

TASK [ovirt.vm-infra : Unset facts] ********************************************************************************************************
task path: /home/vzuser/.ansible/roles/ovirt.vm-infra/tasks/main.yml:50
ok: [localhost] => {
    "ansible_facts": {
        "create_sensitive_vms": [], 
        "create_vms": []
    }, 
    "changed": false
}

Please let me know what may be causing this error. Also let me know if you need additional info..

Other Observation:
I saw the VM getting created in the oVirt manager GUI but it was in DOWN state.
Using the GUI I could bring the VM UP but I was not able to ssh to it using the user name and keys that I had provided in the cloud_init section.

**Comment by mnecas** [comment]
Hi @k8s-junkie,
could you share your playbook so I could recreate this issue, or see what you have done wrong?
And what is your ansible version. (You can copy all `ansible --version`)

**Comment by mnecas** [comment]
I was not able to reproduce also outdated module.
