### ISSUE TITLE
Undefined hosts label with datacenter creation script

### ISSUE THREAD

**Issue by stvnrsnbrg** [oVirt/ovirt-ansible-vm-infra#12]
[datacenter_error.tar.gz](https://github.com/oVirt/ovirt-ansible-vm-infra/files/1756465/datacenter_error.tar.gz)

Attached, please find the ansible script and error dump for this issue. When running the script, the data center is created successfully, but before terminating gives the following error:

fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'hosts' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/oVirt.infra/roles/oVirt.hosts/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Get hosts\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'hosts' is undefined"}
	to retry, use: --limit @/home/srosenbe/ansible/ovirt/my_example/ovirt_infra.retry

**Comment by KKoukiou** [comment]
@stvnrsnbrg hey, sorry for they late reply. I think you opened the issue in the wrong role. I will move it to the relevant role [1] so that we can track it properly.

[1]  https://github.com/oVirt/ovirt-ansible-infra/issues

Can you please close this issue here?

**Comment by stvnrsnbrg** [comment]
OK thank you for the update and for closing the issue.

With Best Regards.

Steven Rosenberg.
