### ISSUE TITLE
Create inventory out of speficied VMs

### ISSUE THREAD

**Issue by machacekondra** [oVirt/ovirt-ansible-vm-infra#32]
Create inventory of VMs. So it's possible to use them in later deployment.

**Comment by cwilkers** [comment]
FYI: 
https://github.com/cwilkers/openshift-ansible/blob/c7e5563cca4583da059a0edaa8f7f09b9e37c431/roles/openshift_rhv/tasks/populate_inventory.yml

**Comment by machacekondra** [comment]
>  https://github.com/cwilkers/openshift-ansible/blob/c7e5563cca4583da059a0edaa8f7f09b9e37c431/roles/openshift_rhv/tasks/populate_inventory.yml

This will create inventory from all VMs in the system, not taking account the password, only ssh keys.
