### ISSUE TITLE
affinity groups required

### ISSUE THREAD

**Issue by arendej** [oVirt/ovirt-ansible-vm-infra#61]
Why is the affinity groups section demanding that the 'vms' dictionary exist?
It might not be requisite in a build.
If this achieves numerous VMs based on the profile template section, then perhaps this would be better if re-done to accept a number and create X number of VMs.

**Comment by machacekondra** [comment]
It shouldn't be required as per:

https://github.com/oVirt/ovirt-ansible-vm-infra/blob/953a55b3f17b85cbee5ff89684d3841e6fa69f7c/tasks/affinity_groups.yml#L2-L20

What's the error you get?
