### ISSUE TITLE
Playbook fails on oVirt.vm-infra : Apply tags from VM profiles

### ISSUE THREAD

**Issue by sradco** [oVirt/ovirt-ansible-vm-infra#65]
TASK [oVirt.vm-infra : Apply tags from VM profiles] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "JMESPathError in json_query filter plugin:\nIn function contains(), invalid type for value: None, expected one of: ['array', 'string'], received: \"null\""}

On rerun this error disappears and playbook ends successfully.

[root@sradco-metrics-1 ovirt-engine-metrics]# rpm -qa|grep ansible
ovirt-ansible-cluster-upgrade-1.1.11-1.el7ev.noarch
ovirt-ansible-repositories-1.1.4-2.el7ev.noarch
ovirt-ansible-engine-setup-1.1.7-1.el7ev.noarch
ovirt-ansible-manageiq-1.1.13-1.el7ev.noarch
ovirt-ansible-disaster-recovery-1.1.3-1.el7ev.noarch
ansible-2.7.6-1.el7ae.noarch
ovirt-ansible-image-template-1.1.9-1.el7ev.noarch
ovirt-ansible-roles-1.1.6-1.el7ev.noarch
ovirt-ansible-shutdown-env-1.0.0-1.el7ev.noarch
ovirt-ansible-vm-infra-1.1.12-1.el7ev.noarch
ovirt-ansible-v2v-conversion-host-1.6.3-2.el7ev.noarch
ovirt-ansible-hosted-engine-setup-1.0.8-1.el7ev.noarch
ovirt-ansible-infra-1.1.11-1.el7ev.noarch

**Comment by machacekondra** [comment]
@mnecas

**Comment by leifmadsen** [comment]
What does the inventory look like?

**Comment by mnecas** [comment]
When you use -vvv, you get:   "msg": "You need to install \"jmespath\" prior to running json_query filter"
you can install it with: "dnf install python-jmespath"

**Comment by sradco** [comment]
@mnecas Thanks Martin! Ill do that. Is it the same package name u/s and d/s?

**Comment by sradco** [comment]
Hi,
This package is installed on the machine that I'm running the playbook from , but playbook still fails:

[root@sradco-metrics-1 ~]# yum info python2-jmespath
Loaded plugins: product-id, search-disabled-repos, subscription-manager, versionlock
Repository rhel-7-server-ose-3.11-rpms is listed more than once in the configuration
Excluding 11 updates due to versionlock (use "yum versionlock status" to show them)
Installed Packages
Name        : python2-jmespath
Arch        : noarch
Version     : 0.9.0
Release     : 4.el7ae
Size        : 132 k
Repo        : installed
Summary     : JSON Matching Expressions
URL         : https://github.com/jmespath/jmespath.py
License     : MIT
Description : JMESPath allows you to declaratively specify how to extract elements from
            : a JSON document.

[root@sradco-metrics-1 ~]# yum whatprovides python2-jmespath
Loaded plugins: product-id, search-disabled-repos, subscription-manager, versionlock
Repository rhel-7-server-ose-3.11-rpms is listed more than once in the configuration
Excluding 11 updates due to versionlock (use "yum versionlock status" to show them)
python2-jmespath-0.9.0-3.el7.noarch : JSON Matching Expressions
Repo        : rhel-7-server-extras-rpms
python2-jmespath-0.9.0-3.el7.noarch : JSON Matching Expressions
Repo        : rhel-extras
python2-jmespath-0.9.0-4.el7ae.noarch : JSON Matching Expressions
Repo        : ansible-27-nightly
python2-jmespath-0.9.0-4.el7ae.noarch : JSON Matching Expressions
Repo        : installed

**Comment by mnecas** [comment]
@sradco Hi could you run the playbook with -vvv and send the error message maybe you have some issue which i cant reproduce.

**Comment by sradco** [comment]
[ovirt-vm-ifra-run.txt](https://github.com/oVirt/ovirt-ansible-vm-infra/files/2918150/ovirt-vm-ifra-run.txt)

**Comment by sradco** [comment]
[ovirt-vm-infra-run.txt](https://github.com/oVirt/ovirt-ansible-vm-infra/files/2918153/ovirt-vm-infra-run.txt)

**Comment by sradco** [comment]
[ovirt-vm-infra-run.txt](https://github.com/oVirt/ovirt-ansible-vm-infra/files/2918160/ovirt-vm-infra-run.txt)

**Comment by machacekondra** [comment]
@sradco can you please share the variables? Or whole playbook you use?

**Comment by sradco** [comment]
```
TASK [/usr/share/ansible/roles/oVirt.metrics/roles/oVirt.origin-on-ovirt : Dictionary for oVirt.vm-infra role for creating the OpenShift vms] ************************************************
ok: [localhost] => {
    "msg": [
        {
            "cloud_init": {
                "authorized_ssh_keys": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8/8csSZ/6rBkUh1OwvZ7yDb63c/L4a1ROPt831ms6bCgzl8NOvujY3iDR9c8Klbm2hi1Z0MpQ8G+dj+WFzLrvtwz+QEMj68dXWBVF9y+Z4SMTaO4cQv4vVeAcTQWYZkvYe2Yf6tDIfMNTowtVUYRhauFKFjdgUo9oJTu5aTXqEzUYj2Dl0YKrpm7rc2CeIE4dO6SCsFyW3FgVPvqGAvrHKSMl5h8vFvupIeNGvdTnNXzALPaFAwnQn3JCMoKYw6uYKQfkq1/R6YKwOSswTGFdi49578h/1aJsbLTi8FI5Zc0+tVFPr/HGtYG+Q1MJBjM6sDAyfFaGarJx1fOuqP8v", 
                "custom_script": "runcmd:\n  - sed -i 's/# ignored_nics =.*/ignored_nics = docker0, tun0 /' etc/ovirt-guest-agent.conf\n  - systemctl enable ovirt-guest-agent\n  - systemctl start ovirt-guest-agent\n  - mkdir -p /var/lib/docker\n  - /usr/sbin/mkfs.xfs -L dockervo /dev/vdb\n  - echo \"Defaults !requiretty\" > /etc/sudoers.d/999-cloud-init-requiretty\n  - mkdir -p '/var/lib/elasticsearch'\n  - /usr/sbin/mkfs.xfs -L elasticvo /dev/vdc\nmounts:\n  - [ '/dev/vdb', '/var/lib/docker', 'xfs', 'defaults,gquota' ]\n  - [ '/dev/vdc', '/var/lib/elasticsearch', 'xfs', 'defaults,gquota' ]\npower_state:\n  mode: reboot\n  message: cloud init finished - boot and install openshift\n  condition: True\n", 
                "root_password": "admin"
            }, 
            "description": "", 
            "host_name": "", 
            "name": "master0.eng.lab.tlv.redhat.com", 
            "profile": {
                "cloud_init": {
                    "authorized_ssh_keys": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8/8csSZ/6rBkUh1OwvZ7yDb63c/L4a1ROPt831ms6bCgzl8NOvujY3iDR9c8Klbm2hi1Z0MpQ8G+dj+WFzLrvtwz+QEMj68dXWBVF9y+Z4SMTaO4cQv4vVeAcTQWYZkvYe2Yf6tDIfMNTowtVUYRhauFKFjdgUo9oJTu5aTXqEzUYj2Dl0YKrpm7rc2CeIE4dO6SCsFyW3FgVPvqGAvrHKSMl5h8vFvupIeNGvdTnNXzALPaFAwnQn3JCMoKYw6uYKQfkq1/R6YKwOSswTGFdi49578h/1aJsbLTi8FI5Zc0+tVFPr/HGtYG+Q1MJBjM6sDAyfFaGarJx1fOuqP8v", 
                    "custom_script": "runcmd:\n  - sed -i 's/# ignored_nics =.*/ignored_nics = docker0, tun0 /' etc/ovirt-guest-agent.conf\n  - systemctl enable ovirt-guest-agent\n  - systemctl start ovirt-guest-agent\n  - mkdir -p /var/lib/docker\n  - /usr/sbin/mkfs.xfs -L dockervo /dev/vdb\n  - echo \"Defaults !requiretty\" > /etc/sudoers.d/999-cloud-init-requiretty\n  - mkdir -p '/var/lib/elasticsearch'\n  - /usr/sbin/mkfs.xfs -L elasticvo /dev/vdc\nmounts:\n  - [ '/dev/vdb', '/var/lib/docker', 'xfs', 'defaults,gquota' ]\n  - [ '/dev/vdc', '/var/lib/elasticsearch', 'xfs', 'defaults,gquota' ]\npower_state:\n  mode: reboot\n  message: cloud init finished - boot and install openshift\n  condition: True\n", 
                    "root_password": "admin"
                }, 
                "cluster": "Default", 
                "cores": 4, 
                "disks": [
                    {
                        "interface": "virtio", 
                        "name": "docker_disk", 
                        "size": "10GiB", 
                        "storage_domain": "vserver_storage"
                    }, 
                    {
                        "interface": "virtio", 
                        "name": "elasticsearch_disk", 
                        "size": "50GiB", 
                        "storage_domain": "vserver_storage"
                    }
                ], 
                "high_availability": true, 
                "memory": "30GiB", 
                "state": "running", 
                "template": "rhelguest76"
            }, 
            "tag": "openshift_master_vm"
        }
    ]
}

TASK [/usr/share/ansible/roles/oVirt.metrics/roles/oVirt.origin-on-ovirt : affinity_groups for oVirt.vm-infra role for creating the OpenShift vms] *******************************************
ok: [localhost] => {
    "msg": []
}
```

**Comment by machacekondra** [comment]
Can you please share how you have defined `vms` variable?

**Comment by sradco** [comment]
It is done with this file 
https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_ovirt/tasks/build_vm_list.yml

**Comment by sradco** [comment]
After further testing I see that this error is consistent and repeates in rerun as well.
It is a blocker for the OpenShift on oVirt metrics installation.

**Comment by sradco** [comment]
This was an issue with vms variable. Closing issue.
