### ISSUE TITLE
Move _Apply any Affinity Groups_ further up the task list?

### ISSUE THREAD

**Issue by leifmadsen** [oVirt/ovirt-ansible-vm-infra#66]
Today I was adding affinity groups to my playbooks, and noticed that the virtual machines would get scheduled across a 3 node cluster onto hosts that didn't match the affinity groups I had configured. At first I thought I had configured the groups wrong, but it turns out that the VMs are scheduled first, then affinity groups are added, which then results (in my case) in the VMs attempting to be migrated across nodes after they have been started.

I was going through the `vm_state_present.yml` file and noticed that the affinity groups tasks are pretty far down the list, after the VMs are started (if your `vm_state` is set to `running` of course).

I think it would be best to move the following lines up a bit further in the task list, just before the virtual machines are started so that when they are scheduled they start up on the appropriate servers, thereby eliminating the migration step.

https://github.com/oVirt/ovirt-ansible-vm-infra/blob/4bc3ca662ab8ac5dd1b840931b5ea9c7a731aae7/tasks/vm_state_present.yml#L100-L101

I'm in the middle of a run right now so I'll test tomorrow, but if this sounds acceptable I will propose a patch and provide testing to validate that it works.

Thanks!

**Comment by machacekondra** [comment]
That sounds very reasonable, will you post a patch? Thanks!

**Comment by leifmadsen** [comment]
Yes I will post a patch next week. I didn't get a chance to create and test it today but this is a high priority for me. Thanks!
