### ISSUE TITLE
Unable to set serial_policy and serial_policy_value for vm or profile

### ISSUE THREAD

**Issue by andreamtp** [oVirt/ovirt-ansible-vm-infra#75]
Description of problem:

When using the ovirt.vm-infra module is not possible to set a custom serial to a VM nor to specify the desired serial-policy

That feature is provided by ovirt-vm [0]

Version-Release number of selected component (if applicable):

ovirt-ansible-vm-infra-1.1.14-1

Steps to Reproduce: 

a playbook example with the expected behaviour

[...]
  vars:

    vm_custom_serial:
      state: running
      cluster: Minion
      serial_policy: custom
      serial_policy_value: my_personal_custom_serial

    vms:
      - name: serial1
        profile: "{{ vm_custom_serial }}"
      - name: serial2
        serial_policy_value: my_personal_custom_serial_just_for_2
        profile: "{{ vm_custom_serial }}"
      - name: serial3
        profile: "{{ vm_custom_serial }}"

  roles:
    - ovirt.vm-infra

Actual results:

Nothing is changed on VMs serial1, serial2 and serial3

Expected results:

A custom serial number is set on those 3 VMs

[0] https://docs.ansible.com/ansible/latest/modules/ovirt_vm_module.html#ovirt-vm-module

**Comment by machacekondra** [comment]
Fixed by #77
