### ISSUE TITLE
wait_for_ip is satisfied with the IPv4 loopback address which is configured by default

### ISSUE THREAD

**Issue by armando82** [oVirt/ovirt-ansible-vm-infra#79]
As a consequence the dynamic VM inventory is being created with "ansible_host": "127.0.0.1" which is useless for subsequent roles. Could it be possible to add another condition to ip_cond to avoid the loopback address. Specially when cloud-init parameters have been defined.

**Comment by armando82** [comment]
Actually it seems like ovirt_vm_facts is only collecting the loopback address in ovirt_vms even after the IPs have been long configured. I'm using the module independently and it gets me the same results.

**Comment by machacekondra** [comment]
That's very strange guest-agent shouldn't return IP address of the loopback device. Do you use ovirt-guest-agent or qemu-guest-agent? What version and what system? But anyway, this is good enhancement, so we will introduce new parameter `wait_for_ip_range`, where you can specify IP range of the IP the user want to wait.

**Comment by armando82** [comment]
Using RHEV 4.2.3.8-0.1.el7 with ovirt-guest-agent. I'm running Ansible from a management VM to create VMs in RHEV from a RHEL7 template, then configuring them with cloud-init.
