### ISSUE TITLE
VM MAC Address can only be set in Profile

### ISSUE THREAD

**Issue by kfp** [oVirt/ovirt-ansible-vm-infra#8]
According to the ovirt-ansible-vm-infra README, the only place the MAC address can be set for a vm is on a profile object. This is not ideal since profiles are supposed to be shared across VMs. The other "nics" params make sense to be shared across groups of VMs but at least MAC address should exist on "vms". Is there a reason the whole "nics" param couldn't simply also exist at the "vms" level as well?

**Comment by machacekondra** [comment]
There is no reason, I will do it, thanks for feedback!
